    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'MainThread'.

sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited

Webhook stopped successfully.

Traceback (most recent call last):

  File "/app/bot.py", line 184, in <module>

    main()

  File "/app/bot.py", line 181, in main

    application.run_polling()

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 832, in run_polling

    return self.__run(

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1024, in __run

    loop = asyncio.get_event_loop()

  File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'MainThread'.

sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited

Webhook stopped successfully.

Traceback (most recent call last):

  File "/app/bot.py", line 184, in <module>

    main()

  File "/app/bot.py", line 181, in main

    application.run_polling()

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 832, in run_polling

    return self.__run(

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1024, in __run

    loop = asyncio.get_event_loop()

  File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'MainThread'.

sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited

Webhook stopped successfully.

Traceback (most recent call last):

  File "/app/bot.py", line 184, in <module>

    main()

  File "/app/bot.py", line 181, in main

    application.run_polling()

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 832, in run_polling

    return self.__run(

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1024, in __run

    loop = asyncio.get_event_loop()

  File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'MainThread'.

sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited

Webhook stopped successfully.

Traceback (most recent call last):

  File "/app/bot.py", line 184, in <module>

    main()

  File "/app/bot.py", line 181, in main

    application.run_polling()

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 832, in run_polling

    return self.__run(

  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1024, in __run

    loop = asyncio.get_event_loop()

  File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'MainThread'.

sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited
